### ISSUE TITLE
Detect and ignore page numbers

### ISSUE THREAD

**Issue by LoneRifle** [opendocsg/pdf2md#10]
Self-explanatory - page numbers are not needed in Markdown since such files are meant to be read online, not as a formal document. Detect the presence of such numbers and eliminate them in the final output

**Comment by jenlky** [comment]
To be fixed by #37 Add removePageNumber and gitignore ExamplePdf.md

**Comment by jenlky** [comment]
Let me get this right. The idea is to implement a filter on `textContent.items` and filter the page number based on a variety of conditions like `page 2 of 5`, `- 5 -`, `5`? Would that suffice?

**Comment by LoneRifle** [comment]
it would be helpful too to consider not just the content of the item, but also its position

**Comment by LoneRifle** [comment]
#38 resulted in a regression. If someone could rework the PR based on feedback on #39 , we could reinstate this feature

**Comment by jenlky** [comment]
I will do it. Let me take a look.

**Comment by LoneRifle** [comment]
Fixed by #41
