### ISSUE TITLE
npm build failing

### ISSUE THREAD

**Issue by 10ego** [opendocsg/pdf2md#35]
Hi guys,
I love the port you did from the original project.
Wanted to check your fork since it had CLI support but I'm having some trouble with the installation phase.
Can you point me to a build script I should run?
e.g. the original project just required me to run a series of npm commands which I've tried to replicate against this version but obviously the build script is missing.

**Comment by LoneRifle** [comment]
Hello @10ego , and thanks for getting in touch! When we forked jzillmann's codebase we decided that we should release the conversion logic as a separate npm package without the front-facing web frontend. As such, part of the codebase you're looking for is probably on [opendocsg/pdf2md-web](https://github.com/opendocsg/pdf2md-web), which pulls this in as a dependency. Hope this helps!

**Comment by 10ego** [comment]
Oof, I should've realized that sooner.  Thank you that makes things even easier.
I now have it set up and working great.

just FYI - it was not able to detect the PDF files if the extension was in all caps (i.e. somefile.PDF) - I just corrected the file extension on my end so it's not a big deal but wanted to knowledge share.

I'll close this ticket since I got it working.
Thanks again!

**Comment by LoneRifle** [comment]
> Oof, I should've realized that sooner. Thank you that makes things even easier.
> I now have it set up and working great.
> 
> just FYI - it was not able to detect the PDF files if the extension was in all caps (i.e. somefile.PDF) - I just corrected the file extension on my end so it's not a big deal but wanted to knowledge share.
> 
> I'll close this ticket since I got it working.
> Thanks again!

Thanks for pointing that out! I don't think it should be too much trouble getting the CLI to recognise file extensions properly, so if you put in a PR, I'll happily review it and have it merged. Alternatively I can try to do it when I find the time.
