### ISSUE TITLE
Questions regarding pdf2md

### ISSUE THREAD

**Issue by berserkwarwolf** [opendocsg/pdf2md#44]
Hi, I tried pdf-to-markdown but it converts most titles to code blocks, and doesn't support image extraction. Is pdf2md any different in this regard ? What major changes have you done to upstream ?

**Comment by LoneRifle** [comment]
Hi @berserkwarwolf and thanks for looking at this library!

The main differences between pdf-to-markdown and this fork largely centre around how paragraphs are aggregated, as well as the detection and elimination of page numbers (see #38). 

It similarly does not support image extraction as that would be a non-trivial exercise. Another nice-to-have that I wished I had the time to implement would be table extraction, which is done using OCR in Camelot, the PDF extractor Python library.

pdf2md solely contains the actual biz logic from pdf-to-markdown that reads the PDF blob and converts to appropriate Markdown. As such, it has been ported to vanilla JavaScript, with some invasive changes to the extraction process to remove its dependency on React (bfc729b). A CLI tool has also been built around it. Meanwhile, the UI parts of this port have been moved to [pdf2md-web](https://github.com/opendocsg/pdf2md-web), which pulls in pdf2md as an npm dependency.

**Comment by berserkwarwolf** [comment]
Is there any demo site I can try ? I am a non-technical person using Windows. I want to know if it's the right tool for my use case, if so, I can hire someone to implement it for me.

**Comment by LoneRifle** [comment]
There isn't unfortunately, though you may persuade someone else to read this discussion and see if he or she can put something together for you.
